version: '3'
services: 
  web:
    build: 
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - '4200:4200'
    volumes:
      - .:/home/nodejs/myapp
      - /home/nodejs/myapp/node_modules