FROM node:8-alpine

EXPOSE 4200

ENV HOME=/home/nodejs
ENV APP_NAME=myapp
ENV PATH $HOME/$APP_NAME/node_modules/.bin:$PATH

WORKDIR $HOME/$APP_NAME

COPY package.json .
RUN npm set progress=false && npm config set depth 0 && npm cache clean --force
RUN npm i
# && mkdir -p $HOME/$APP_NAME && cp -R ./node_modules $HOME/$APP_NAME


#ADD ../../ $HOME/$APP_NAME/

RUN ls -ltr $HOME/$APP_NAME/

#CMD ["ng", "serve", "--host", "0.0.0.0" ]

CMD ["npm", "start"]